# Generated by Django 5.1.3 on 2024-11-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_created_at'),
        ('store', '0004_category_updated_at'),
    ]

    operations = [
    ]
